<table>
    <tr>
        <td><h2><?php echo $this->__("Introduciendo...") ?></h2></td>
        <td>&nbsp;</td>
        <td><img src='<?php echo $this->getSkinUrl('images/redsys/mastercard_secuercode.png') ?>' width='116' /></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__("MasterCard (r) SecureCode(tm) es un nuevo servicio de MasterCard y de su emisor de tarjeta que proporciona proteccion adicional cuando usted realiza compras online. No hay necesidad de obtener una nueva tarjeta MasterCard o Maestro(r). Usted escoge su propio MasterCard SecureCode personal y este nunca es compartido con ningun comercio. Un codigo privado significa proteccion adicional contra el uso no autorizado de su tarjeta de credito y de debito cuando usted compre online.") ?><td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__('Cada vez que pague online con su tarjeta MasterCard o Maestro, una ventana que proviene de su emisor de tarjeta se abre preguntandole por su SecureCode personal, tal como su banco le pregunta en el cajero automatico. En segundos, su emisor de tarjeta confirma que es usted y le permite completar su compra.') ?></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td><img src='<?php echo $this->getSkinUrl('images/redsys/mastercard.png') ?>' width='72' /></td>
        <td><?php echo $this->__('Para obtener mas informacion sobre MasterCard SecureCode dirijase a <a href="http://www.mastercardsecurecode.com">www.mastercardsecurecode.com</a>') ?></td>
        <td><img src='<?php echo $this->getSkinUrl('images/redsys/maestro.png') ?>' width='72' /></td>
    </tr>
    <tr>
        <td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Cerrar ventana') ?></button></td>
    </tr>
</table>