<script type="text/javascript" src='<?php echo Mage::getBaseUrl('js') ?>standardwindow.js'></script>
<?php echo $this->getFormRedirect(); ?>
<center>
    <?php if(3 == $this->getWindowstate()){ ?>
        <iframe name='integrado' style='overflow: hidden;width: 740px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; border-image: initial; height: 470px;' marginheight='0' marginwidth='0' scrolling='no'></iframe>
    <?php } else { ?>
        <h3><?php echo $this->__('Al pinchar en continuar te derivaremos a la pasarela de pago de Redsýs, ningún dato de la tarjeta se guarda en nuestros servidores, lo que hace los pagos 100% seguros.') ?></h3><br /><br />
        <a href='<?php echo Mage::getUrl("redsys/standard/visa/") ?>' target="_blank">
            <img src='<?php echo $this->getSkinUrl('images/redsys/verifiedbyvisa.png') ?>' border="0" />
        </a>&nbsp;&nbsp;
        <a href='<?php echo Mage::getUrl("redsys/standard/mastercard/") ?>' target="_blank">
            <img src='<?php echo $this->getSkinUrl('images/redsys/mastercard_secuercode.png') ?>' border="0" />
        </a><br />
    <?php } ?>
    <?php if(3 == $this->getWindowstate()){ ?>
        <script type="text/javascript">
            document.getElementById("redsys_standard_checkout").target = 'integrado';
            document.getElementById("redsys_standard_checkout").submit();
        </script>
    <?php } else if(1 == $this->getWindowstate()){ ?>
        <input class="form-button" type="button" onclick="open_Redsys_window();" value='<?php echo $this->__('Enviar') ?>' />
        <script type="text/javascript">open_Redsys_window();</script>
    <?php } else { ?>
        <input class="form-button" type="button" onclick="document.getElementById('redsys_standard_checkout').submit();"  value='<?php echo $this->__('Enviar') ?>' />
        <script type="text/javascript">document.getElementById("redsys_standard_checkout").submit()</script>
    <?php } ?>
</center>
